# Generated by Django 5.0.6 on 2024-07-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_product_category_1_alter_product_category_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category_1',
            field=models.CharField(choices=[('all', 'All'), ('mobile_phones_accessories', 'Mobile Phones & Accessories'), ('computers_accessories', 'Computers & Accessories'), ('wearable_technology', 'Wearable Technology'), ('smart_home_devices', 'Smart Home Devices'), ('jewelry', 'Jewelry'), ('bags_wallets', 'Bags & Wallets'), ('watches', 'Watches'), ('hair_accessories', 'Hair Accessories'), ('women_unstitch', 'Women Unstitch'), ('men_unstitch', 'Men Unstitch'), ('women_stitched', 'Women Stitched'), ('men_stitched', 'Women Stitched'), ('health_beauty', 'Health & Beauty'), ('baby_products', 'Baby Products')], default='all', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_2',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('mobile_phones_accessories', 'Mobile Phones & Accessories'), ('computers_accessories', 'Computers & Accessories'), ('wearable_technology', 'Wearable Technology'), ('smart_home_devices', 'Smart Home Devices'), ('jewelry', 'Jewelry'), ('bags_wallets', 'Bags & Wallets'), ('watches', 'Watches'), ('hair_accessories', 'Hair Accessories'), ('women_unstitch', 'Women Unstitch'), ('men_unstitch', 'Men Unstitch'), ('women_stitched', 'Women Stitched'), ('men_stitched', 'Women Stitched'), ('health_beauty', 'Health & Beauty'), ('baby_products', 'Baby Products')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_3',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('mobile_phones_accessories', 'Mobile Phones & Accessories'), ('computers_accessories', 'Computers & Accessories'), ('wearable_technology', 'Wearable Technology'), ('smart_home_devices', 'Smart Home Devices'), ('jewelry', 'Jewelry'), ('bags_wallets', 'Bags & Wallets'), ('watches', 'Watches'), ('hair_accessories', 'Hair Accessories'), ('women_unstitch', 'Women Unstitch'), ('men_unstitch', 'Men Unstitch'), ('women_stitched', 'Women Stitched'), ('men_stitched', 'Women Stitched'), ('health_beauty', 'Health & Beauty'), ('baby_products', 'Baby Products')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_4',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('mobile_phones_accessories', 'Mobile Phones & Accessories'), ('computers_accessories', 'Computers & Accessories'), ('wearable_technology', 'Wearable Technology'), ('smart_home_devices', 'Smart Home Devices'), ('jewelry', 'Jewelry'), ('bags_wallets', 'Bags & Wallets'), ('watches', 'Watches'), ('hair_accessories', 'Hair Accessories'), ('women_unstitch', 'Women Unstitch'), ('men_unstitch', 'Men Unstitch'), ('women_stitched', 'Women Stitched'), ('men_stitched', 'Women Stitched'), ('health_beauty', 'Health & Beauty'), ('baby_products', 'Baby Products')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_5',
            field=models.CharField(blank=True, choices=[('all', 'All'), ('mobile_phones_accessories', 'Mobile Phones & Accessories'), ('computers_accessories', 'Computers & Accessories'), ('wearable_technology', 'Wearable Technology'), ('smart_home_devices', 'Smart Home Devices'), ('jewelry', 'Jewelry'), ('bags_wallets', 'Bags & Wallets'), ('watches', 'Watches'), ('hair_accessories', 'Hair Accessories'), ('women_unstitch', 'Women Unstitch'), ('men_unstitch', 'Men Unstitch'), ('women_stitched', 'Women Stitched'), ('men_stitched', 'Women Stitched'), ('health_beauty', 'Health & Beauty'), ('baby_products', 'Baby Products')], max_length=100),
        ),
    ]
