# Generated by Django 5.0.6 on 2024-07-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0010_alter_product_category_1_alter_product_category_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_1',
        ),
        migrations.AddField(
            model_name='product',
            name='price_without_discount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
